// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uorgwbjcymjmqxdcrnvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvcmd3YmpjeW1qbXF4ZGNybnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNjc5MzUsImV4cCI6MjA1NDk0MzkzNX0.ZPsDJVaVWna97tYdf0GnLSVVUlqJGNHHZpNPcK0Akyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);